// Copyright (C) 2026 Techdelight BV

package main

import (
	"fmt"

	"github.com/techdelight/daedalus/internal/color"
)

// printUsage prints the CLI usage message.
func printUsage() {
	fmt.Println(color.Bold("Daedalus") + " — hands-off AI coding agents in a safe, isolated Docker container.")
	fmt.Println("Your agent runs autonomously with no permission prompts; the container can")
	fmt.Println("only touch the project directory. Detach and reattach from anywhere.")
	fmt.Println()
	fmt.Printf("%s daedalus [flags] <project-name> [project-dir]\n", color.Bold("Usage:"))
	fmt.Println("       daedalus init [--force] [--no-scaffold] [dir]")
	fmt.Println("       daedalus --build")
	fmt.Println("       daedalus list")
	fmt.Println("       daedalus prune")
	fmt.Println("       daedalus remove <name> [name...]")
	fmt.Println("       daedalus rename <old-name> <new-name>")
	fmt.Println("       daedalus config <project-name> [--set key=value] [--unset key]")
	fmt.Println("       daedalus tui")
	fmt.Println("       daedalus web [--port PORT] [--host HOST] [--auth|--no-auth]")
	fmt.Println("       daedalus skills [add <file> | remove <name> | show <name>]")
	fmt.Println("       daedalus runners [list | show <name>]")
	fmt.Println("       daedalus personas [list | show <name> | create <name> | remove <name>]")
	fmt.Println("       daedalus programmes [list | show <name> | status <name> [--suggest-deps] |")
	fmt.Println("                           create <name> <what-it-is-for> |")
	fmt.Println("                           add-project <programme> <project> | add-dep <programme> <up> <down> |")
	fmt.Println("                           remove <name>]")
	fmt.Println("       daedalus coordinator [start | stop | status]")
	fmt.Println("       daedalus control [start | stop | restart | status]")
	fmt.Println("       daedalus completion <bash|zsh|fish>")
	fmt.Println("       daedalus version [list | use <version> | rollback | prune [--keep N]]")
	fmt.Println("       daedalus task [create | list | status <id> | dispatch <id> | verify <id> |")
	fmt.Println("                      review <id> | approve <id> | reject <id> | integrate <id> |")
	fmt.Println("                      approvals | proposals | depends <id> | steer <job-id> |")
	fmt.Println("                      board | target | adopt [<project>] |")
	fmt.Println("                      retry <id> [--rebase] | reverify <id> [--amended] |")
	fmt.Println("                      checks <id> | budget <id> [--attempts <n>] |")
	fmt.Println("                      replan <id> --objective <text> [--rebase] |")
	fmt.Println("                      refine <id> [--from-review <RV-n>] [--note <text>] |")
	fmt.Println("                      events <id> |")
	fmt.Println("                      cancel <id>]")
	fmt.Println("       daedalus --help")
	fmt.Println()
	fmt.Println(color.Bold("Commands:"))
	fmt.Println("  init [dir]                    Scaffold project docs and print a getting-started guide")
	fmt.Println("  <project-name>                Open a registered project (uses stored directory)")
	fmt.Println("  <project-name> <project-dir>  Register and open a new project")
	// `build` is a dispatched subcommand as well as a flag, and only the flag was
	// listed — so `daedalus build` existed in the code and nowhere a reader could
	// find it. Found by tightening the test below, which had been satisfied by
	// "--build" containing the word.
	fmt.Println("  build | --build               Rebuild images for all registered projects")
	fmt.Println("  list                          List all registered projects")
	fmt.Println("  prune                         Remove registry entries with missing directories")
	fmt.Println("  remove <name> [name...]       Remove named projects from the registry")
	fmt.Println("  rename <old> <new>            Rename a registered project")
	fmt.Println("  config <name>                 View or edit per-project default flags")
	fmt.Println("  tui                           Interactive dashboard for managing projects")
	fmt.Println("  web                           Web UI dashboard (default: localhost:3000, auto-detects WSL2)")
	fmt.Println("  skills                        List, add, remove, or show skills in the shared catalog")
	fmt.Println("  runners                       List or show built-in runner profiles (claude, copilot)")
	fmt.Println("  personas                      List, show, create, or remove named persona configurations")
	fmt.Println("  docs lint [--ci] [dir]        Check ROADMAP.md/SPRINTS.md against the dashboard-arc format")
	fmt.Println("  docs scaffold [--force] [dir] Write conformant project-doc skeletons into dir")
	fmt.Println("  completion <shell>            Print shell completion script (bash, zsh, fish)")
	fmt.Println("  version list|use|rollback     Manage side-by-side installed versions (prune to clean up)")
	fmt.Println("  task create|list|status|dispatch|verify|review|approve|reject|integrate")
	fmt.Println("       |approvals|proposals|depends|steer|board|target|retry|reverify|checks")
	fmt.Println("       |budget|replan|refine|events|cancel")
	fmt.Println("                                Host-side control-plane tasks (budgets, verification,")
	fmt.Println("                                independent review, approval, race-safe integration,")
	fmt.Println("                                event log). Ids: T-n task, J-n job, A-n artifact,")
	fmt.Println("                                RV-n review, P-n proposal, PR-n programme")
	fmt.Println("  programmes                    Shared intent across projects: what several tasks are FOR.")
	fmt.Println("                                `status` rolls up the work serving a programme and what it")
	fmt.Println("                                is waiting on outside itself")
	fmt.Println("  coordinator start|stop|status Host-side session daemon (auto-spawned; stop it to pick up")
	fmt.Println("                                a rebuilt image or binary)")
	fmt.Println("  control start|stop|restart|status")
	fmt.Println("                                The control-plane daemon (auto-spawned by `task` and")
	fmt.Println("                                `programmes`). `restart` after an upgrade: a running")
	fmt.Println("                                daemon serves the routes it was BUILT with")
	fmt.Println("  guild-master                  Open the built-in cross-project overseer. It reads every")
	fmt.Println("                                registered project read-only and proposes; it cannot act")
	fmt.Println()
	fmt.Println(color.Bold("Flags:"))
	fmt.Println("  --build            Force rebuild the Docker image (standalone: rebuild all)")
	fmt.Println("  --target <stage>   Build target: dev (default), godot, base, utils")
	fmt.Println("  --resume <id>      Resume a previous Claude session")
	fmt.Println("  -p <prompt>        Run a headless single-prompt task")
	fmt.Println("  --debug            Enable Claude Code debug mode")
	fmt.Println("  --dind             Mount Docker socket (WARNING: grants host Docker access)")
	fmt.Println("  --display          Forward host display (X11/Wayland) into the container")
	fmt.Println("  --force            Force deletion in non-interactive mode (e.g. prune)")
	fmt.Println("  --runner <name>    AI runner: claude (default) or copilot")
	fmt.Println("  --persona <name>   Named persona configuration to use")
	fmt.Println("  --container-log    Log container output to <data-dir>/<project>/container.log")
	fmt.Println("  --no-color         Disable colored output (also honors NO_COLOR env var)")
	fmt.Println("  --port <port>      Port for web UI (default: 3000)")
	fmt.Println("  --host <host>      Host for web UI (default: 127.0.0.1, 0.0.0.0 on WSL2)")
	fmt.Println("  --auth             Enable token-based authentication for web UI (default)")
	fmt.Println("  --no-auth          Disable authentication for web UI (also exposes the")
	fmt.Println("                     control-plane approve/reject buttons — see README)")
	fmt.Println("  --help, -h         Show this help message")
	fmt.Println()
	fmt.Println(color.Bold("Examples:"))
	fmt.Println("  daedalus init                           Scaffold docs here and show getting-started steps")
	fmt.Println("  daedalus my-app                         Open existing project from registry")
	fmt.Println("  daedalus my-app /path/to/project        Register and open a new project")
	fmt.Println("  daedalus my-app -p \"Fix linting errors\" Run a headless task")
	fmt.Println("  daedalus --build                        Rebuild images for all projects")
	fmt.Println("  daedalus --build --target godot          Rebuild only the godot target image")
	fmt.Println("  daedalus --build --target godot my-game /path/to/game")
	fmt.Println("  daedalus list                           Show all registered projects")
	fmt.Println("  daedalus https://github.com/user/repo    Clone and register a GitHub repo")
	fmt.Println("  daedalus user/repo                       Shorthand for GitHub repos")
	fmt.Println("  daedalus config my-app --set target=godot Switch build target")
	fmt.Println("  daedalus web --port 8080                Start web UI on port 8080")
	fmt.Println("  daedalus web --no-auth                  Web UI without authentication")
	fmt.Println("  daedalus rename my-app my-new-app        Rename a project")
	fmt.Println("  daedalus config my-app --set dind=true  Set per-project default")
	fmt.Println("  daedalus --runner copilot my-app          Use Copilot CLI instead of Claude")
	fmt.Println("  daedalus runners                        List built-in runners")
	fmt.Println("  daedalus personas create reviewer       Create a persona configuration")
	fmt.Println("  daedalus --persona reviewer my-app       Use a custom persona")
	fmt.Println("  daedalus completion bash                Print bash completion script")
}
