// Copyright (C) 2026 Techdelight BV

package main

import (
	"fmt"

	"github.com/techdelight/daedalus/internal/color"
)

// printUsage prints the CLI usage message.
func printUsage() {
	fmt.Printf("%s daedalus [flags] <project-name> [project-dir]\n", color.Bold("Usage:"))
	fmt.Println("       daedalus --build")
	fmt.Println("       daedalus list")
	fmt.Println("       daedalus prune")
	fmt.Println("       daedalus remove <name> [name...]")
	fmt.Println("       daedalus rename <old-name> <new-name>")
	fmt.Println("       daedalus config <project-name> [--set key=value] [--unset key]")
	fmt.Println("       daedalus tui")
	fmt.Println("       daedalus web [--port PORT] [--host HOST] [--auth|--no-auth]")
	fmt.Println("       daedalus skills [add <file> | remove <name> | show <name>]")
	fmt.Println("       daedalus runners [list | show <name>]")
	fmt.Println("       daedalus personas [list | show <name> | create <name> | remove <name>]")
	fmt.Println("       daedalus completion <bash|zsh|fish>")
	fmt.Println("       daedalus --help")
	fmt.Println()
	fmt.Println(color.Bold("Commands:"))
	fmt.Println("  <project-name>                Open a registered project (uses stored directory)")
	fmt.Println("  <project-name> <project-dir>  Register and open a new project")
	fmt.Println("  --build                       Rebuild images for all registered projects")
	fmt.Println("  list                          List all registered projects")
	fmt.Println("  prune                         Remove registry entries with missing directories")
	fmt.Println("  remove <name> [name...]       Remove named projects from the registry")
	fmt.Println("  rename <old> <new>            Rename a registered project")
	fmt.Println("  config <name>                 View or edit per-project default flags")
	fmt.Println("  tui                           Interactive dashboard for managing projects")
	fmt.Println("  web                           Web UI dashboard (default: localhost:3000, auto-detects WSL2)")
	fmt.Println("  skills                        List, add, remove, or show skills in the shared catalog")
	fmt.Println("  runners                       List or show built-in runner profiles (claude, copilot)")
	fmt.Println("  personas                      List, show, create, or remove named persona configurations")
	fmt.Println("  completion <shell>            Print shell completion script (bash, zsh, fish)")
	fmt.Println()
	fmt.Println(color.Bold("Flags:"))
	fmt.Println("  --build            Force rebuild the Docker image (standalone: rebuild all)")
	fmt.Println("  --target <stage>   Build target: dev (default), godot, base, utils")
	fmt.Println("  --resume <id>      Resume a previous Claude session")
	fmt.Println("  -p <prompt>        Run a headless single-prompt task")
	fmt.Println("  --no-tmux          Run without tmux session wrapping")
	fmt.Println("  --debug            Enable Claude Code debug mode")
	fmt.Println("  --dind             Mount Docker socket (WARNING: grants host Docker access)")
	fmt.Println("  --display          Forward host display (X11/Wayland) into the container")
	fmt.Println("  --force            Force deletion in non-interactive mode (e.g. prune)")
	fmt.Println("  --runner <name>    AI runner: claude (default) or copilot")
	fmt.Println("  --persona <name>   Named persona configuration to use")
	fmt.Println("  --container-log    Log container output to <data-dir>/<project>/container.log")
	fmt.Println("  --no-color         Disable colored output (also honors NO_COLOR env var)")
	fmt.Println("  --port <port>      Port for web UI (default: 3000)")
	fmt.Println("  --host <host>      Host for web UI (default: 127.0.0.1, 0.0.0.0 on WSL2)")
	fmt.Println("  --auth             Enable token-based authentication for web UI (default)")
	fmt.Println("  --no-auth          Disable authentication for web UI")
	fmt.Println("  --help, -h         Show this help message")
	fmt.Println()
	fmt.Println(color.Bold("Examples:"))
	fmt.Println("  daedalus my-app                         Open existing project from registry")
	fmt.Println("  daedalus my-app /path/to/project        Register and open a new project")
	fmt.Println("  daedalus my-app -p \"Fix linting errors\" Run a headless task")
	fmt.Println("  daedalus --build                        Rebuild images for all projects")
	fmt.Println("  daedalus --build --target godot          Rebuild only the godot target image")
	fmt.Println("  daedalus --build --target godot my-game /path/to/game")
	fmt.Println("  daedalus list                           Show all registered projects")
	fmt.Println("  daedalus https://github.com/user/repo    Clone and register a GitHub repo")
	fmt.Println("  daedalus user/repo                       Shorthand for GitHub repos")
	fmt.Println("  daedalus config my-app --set target=godot Switch build target")
	fmt.Println("  daedalus web --port 8080                Start web UI on port 8080")
	fmt.Println("  daedalus web --no-auth                  Web UI without authentication")
	fmt.Println("  daedalus rename my-app my-new-app        Rename a project")
	fmt.Println("  daedalus config my-app --set dind=true  Set per-project default")
	fmt.Println("  daedalus --runner copilot my-app          Use Copilot CLI instead of Claude")
	fmt.Println("  daedalus runners                        List built-in runners")
	fmt.Println("  daedalus personas create reviewer       Create a persona configuration")
	fmt.Println("  daedalus --persona reviewer my-app       Use a custom persona")
	fmt.Println("  daedalus completion bash                Print bash completion script")
}
